//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders_Test
    {
        public int ID_Order { get; set; }
        public Nullable<int> ID_Customer { get; set; }
        public Nullable<int> ID_Product { get; set; }
        public Nullable<int> Quantity_O { get; set; }
    
        public virtual Customer_C Customer_C { get; set; }
        public virtual Product_Test Product_Test { get; set; }
    }
}
